plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-teaching-cs.github.io 
baseurl: "/s19"  
github_url: https://github.com/ucsb-teaching-cs/s19

title: "UCSB Teaching CS"
course: "CS190J"
qtr: "S19"
quarter: "Spring 2019"
ta_list: ""
ta_list_full: ""
instructor: "Mirza"


start_week: 1
start_date: 2019-03-31 
num_weeks: 10
extra_exam_week: true


cal_dates: >
  [
  {"label":"First day of classes", "date":"2019-05-01" },
  {"label":"Univ Holiday", "date":"2019-05-27" },
  {"label":"Drop deadline (no W grade)","date":"2019-04-26" },
  {"label":"S19 Instruction Ends", "date":"2019-06-07" },  
  {"label":"S19 Quarter Ends", "date":"2019-06-14" }          
  ]


kramdown:
   parse_block_html: true
   default_lang: python


exclude:
   - vendor
include:
   - _pages

timezone: America/Los_Angeles

collections:
  papers:
    output: true
    permalink: /hwk/:path/
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: info
    values:
      layout: info
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout


